---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      - kitchen/dokken-single:
          name: default
          suite: default
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: redis-package
          suite: redis-package
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: sentinel
          suite: sentinel
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: multisentinel
          suite: multisentinel
          requires:
            *lint_and_unit
